[project]
name = "pub2btc"
authors = ["j2p2"]
description = "library for converting public keys to bitcoin addresses"
telemetry = false
requirements = []
analysis = ["check_checker"]
costs_version = 2
[contracts.pub2btc]
path = "contracts/pub2btc.clar"
depends_on = []
